### ISSUE TITLE
Dropdown not working with 2.1.1? - Uncaught TypeError: e.querySelectorAll is not a function

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#607]
Trying to create a [dropdown](https://www.sceditor.com/api/sceditor/createdropdown/) with SCeditor's [custom commands](https://www.sceditor.com/documentation/custom-commands/). However, just getting: 

> Uncaught TypeError: e.querySelectorAll is not a function

Fiddle: http://jsfiddle.net/wa5jvtcy/7/

	$(document).ready(function()
	{
		
	  // Special Chars Command
	  sceditor.command.set('specialchars', 
	  {
		// wysiswyg mode 
		exec: function(caller) 
		{
		  var editor  = this;

		  var special_chars = [ '&plusmn;', '&minus;', '&radic;', '&pi;', '&isin;'];

		  var sce_schars = '<div id="sce_specialcharsbox">';
		  $.each( special_chars, function( key, value ) 
		  {
			// console.log( key + ": " + value );
			sce_schars += '<div class="sce_char"><span>'+value+'</span></div>';
		  });
		  sce_schars += '</div>'; // end sce_specialcharsbox

		  drop_content = $(sce_schars);

		  drop_content.find('.sce_char').click( function(e) 
		  {
			var htmlchar = $(this).text();
			editor.insert(htmlchar);
			editor.closeDropDown(true);
		  });

		  // dropdown
		  editor.createDropDown(caller, 'specialchars-wrap', drop_content);
		},

		// txtExec: function() {}, // source mode 

		tooltip: 'Insert special characters'

	  });

	  var textarea = document.getElementById('demo-ta');
	  sceditor.create(textarea, {
		  format: 'xhtml',
		  toolbar: 'specialchars,bold,underline,italic',
		  style: 'https://cdn.jsdelivr.net/npm/sceditor@2/minified/themes/content/default.min.css',
		  emoticonsEnabled: false,
	  });
	});

It worked with sceditor 1.0 as I can remember.

**Comment by q2apro** [comment]
Fixed it by: 

    editor.createDropDown(caller, 'specialchars-wrap', drop_content[0]);

I hope this example / demo will help others to create a custom dropdown.
